drop table if exists temporary_links_pair;

alter table links_pair
    add column if not exists expired_in timestamp with time zone;
alter table links_pair
    drop constraint if exists pk_links_pair cascade;
alter table links_pair drop constraint if exists u_short_link cascade;
alter table links_pair
    add constraint u_short_link unique (short_link);
alter table links_pair
    add column if not exists id int primary key generated by default as identity;