create table if not exists verify_email_code(
    email varchar primary key,
    verify_code varchar not null
);

create table if not exists client(
    id int primary key generated by default as identity,
    username varchar not null unique,
    email varchar unique
);